# build stage
FROM node:18-alpine AS build
WORKDIR /app

COPY client/package*.json ./
RUN npm ci
COPY client/ ./
RUN npm run build

# production stage
FROM nginx:stable-alpine

# copy custom nginx config
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# copy built app
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]